# Generated by Django 4.1.5 on 2023-03-02 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=32)),
                ('first_color', models.CharField(blank=True, max_length=7, null=True)),
                ('second_color', models.CharField(blank=True, max_length=7, null=True)),
                ('font_color', models.CharField(blank=True, max_length=7, null=True)),
                ('font_size', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(24)])),
                ('theme_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='blog.author')),
            ],
        ),
    ]
