# Generated by Django 4.1.5 on 2023-03-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
